<?php

namespace Database\Seeders\Analysis;

use Illuminate\Database\Seeder;
use App\Models\Person\User;
use App\Models\Sydelab\Sucursal;
use App\Models\Sydelab\ConfigInterpretationParameter;
use App\Models\Analysis\Exams;
use App\Models\Analysis\RelationSamplesHeader;
use App\Models\Analysis\RelationSamplesDetails;
use App\Models\Analysis\Samples;
use App\Models\Analysis\TypeExams;
use App\Models\Analysis\CategoryExams;
use App\Models\Analysis\TypeParameterTemplate;
use App\Models\Analysis\ScaleParameterAge;
use App\Models\Analysis\TypeAdjustPrice;

class AnalysisSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //---1-MATRIZ NECESARIA PARA CREAR LOS REGISTROS, DEBE ESTAR YA CREADA LA MATRIZ
        $matriz = Sucursal::where('matriz', 'MATRIZ')->first();
        //---2-USUARIO DEFAULT, TAMBIEN YA DEBE ESTAR CREADO PARA INSERTAR LOS SIGUIENTES REGISTROS
        $user = User::where('protected', 'ACTIVO')->where('user_first', 'ACTIVO')->first();

        if (isset($user) && isset($matriz)) {
            //--- CREACION DE EXAMENES
            $arr_distribution = [
                ['samples' => ['Orina'], 'code' => 'EMO', 'name' => 'ELEMENTAL Y MICROSCÓPICO DE ORINA', 'name_report' => 'EMO', 'hour_process' => 2],
                ['samples' => ['Suero (Rojo)'], 'code' => 'COL', 'name' => 'COLESTEROL', 'name_report' => null, 'hour_process' => 5],
                ['samples' => ['Suero (Rojo)'], 'code' => 'FT4', 'name' => 'TIROXINA T4 LIBRE', 'name_report' => 'FT4', 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'TRI', 'name' => 'TRIGLICÉRIDOS', 'name_report' => 'TRI', 'hour_process' => 4],
                ['samples' => ['Suero (Rojo)'], 'code' => '17OH', 'name' => '17-OH-PROGESTERONA', 'name_report' => '17-OH', 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'FOSLIG', 'name' => 'ANTICUERPOS ANTIFOSFOLIPIDOS IgG', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'FOSLIM', 'name' => 'ANTICUERPOS ANTIFOSFOLIPIDOS IGM', 'name_report' => 'ANTI-FOSFO-IGM', 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ACENDG', 'name' => 'ANTIENDOMISIO IgG', 'name_report' => 'ENDOMISIO IGG', 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'AFOL', 'name' => 'ÁCIDO FÓLICO', 'name_report' => 'A. FOLICO', 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ALACT', 'name' => 'ÁCIDO LÁCTICO (LACTATO)', 'name_report' => 'AC. LÁCTICO', 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'AU', 'name' => 'ÁCIDO ÚRICO', 'name_report' => 'AU', 'hour_process' => 3],
                ['samples' => ['Orina'], 'code' => 'AUO', 'name' => 'ÁCIDO ÚRICO EN ORINA', 'name_report' => 'AU ORINA', 'hour_process' => 3],
                ['samples' => ['Suero (Rojo)'], 'code' => 'AVAL', 'name' => 'ÁCIDO VALPRÓICO', 'name_report' => 'A. VALPRO', 'hour_process' => 24],
                ['samples' => ['Plasma (Verde)', 'Hisopado Nasofaringeo'], 'code' => 'ADENO', 'name' => 'Adenovirus por ADN/PCR', 'name_report' => 'ADENO', 'hour_process' => 72],
                ['samples' => ['Suero (Rojo)'], 'code' => 'WIDAL', 'name' => 'AGLUTINACIONES FEBRILES (REACCIÓN DE WIDAL)', 'name_report' => 'FEBRILES', 'hour_process' => 5],
                ['samples' => ['Suero (Rojo)'], 'code' => 'TGP', 'name' => 'ALANINO AMINOTRANSFERASA GPT (ALT)', 'name_report' => 'TGP', 'hour_process' => 3],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ALBU', 'name' => 'ALBÚMINA', 'name_report' => 'ALBU', 'hour_process' => 3],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ALDO', 'name' => 'ALDOLASA', 'name_report' => 'ALDO', 'hour_process' => 72],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ANABLO', 'name' => 'ANA BLOT PANEL 17 ANTIGENOS', 'name_report' => 'ANA BLOT', 'hour_process' => 72],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ANDROS', 'name' => 'ANDROSTENEDIONA', 'name_report' => 'ANDROSTE', 'hour_process' => 48],
                ['samples' => ['Orina'], 'code' => 'ANFE', 'name' => 'ANFETAMINAS', 'name_report' => 'ANFET', 'hour_process' => 5],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ANTIVI', 'name' => 'ANTI VIMENTINA', 'name_report' => 'ANTI VIMEN', 'hour_process' => 96],
                ['samples' => ['Suero (Rojo)'], 'code' => 'B2GP1M', 'name' => 'ANTI-BETA 2 GLICOPROTEINA I IGM', 'name_report' => 'B2 GLICO IGM', 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ACCP', 'name' => 'ANTI-CCP (CITRULINA)', 'name_report' => 'ANTI CCP', 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ADNA', 'name' => 'ANTI-DNA', 'name_report' => 'ANTI-DNA C.S.', 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'AFOSIG', 'name' => 'ANTI-FOSFATIDIL SERINA IGG', 'name_report' => 'ANTI-FOS. SERIN', 'hour_process' => 96],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ANCAP', 'name' => 'ANTI-MPO (ANCA-P)', 'name_report' => 'ANCA-P', 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ANCAC', 'name' => 'ANTI-PR3 (ANCA-C)', 'name_report' => 'ANCA-C', 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ATG', 'name' => 'ANTI-TIROGLOBULINA', 'name_report' => 'ATG', 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ATPO', 'name' => 'ANTI MICROSOMALES (TPO) (PEROXIDASA TIROIDEA)', 'name_report' => 'ATPO', 'hour_process' => 24],
                ['samples' => ['Antibiograma'], 'code' => 'ANTIB', 'name' => 'ANTIBIOGRAMA', 'name_report' => 'ANTIBIO', 'hour_process' => 72],
                ['samples' => ['Suero (Rojo)'], 'code' => 'CARDIA', 'name' => 'ANTICARDIOLIPINA IgA', 'name_report' => 'ANTI CARDIO IGA', 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'CARDIG', 'name' => 'ANTICARDIOLIPINA IgG', 'name_report' => 'ANTI CARDIO IGG', 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'CARDIM', 'name' => 'ANTICARDIOLIPINA IgM', 'name_report' => 'ANTI CARDIO IGM', 'hour_process' => 48],
                ['samples' => ['Sangre Citrato (Celeste)'], 'code' => 'LUPICO', 'name' => 'ANTICOAGULANTE LÚPICO', 'name_report' => 'ANTIC. LUPICO', 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ANTILA', 'name' => 'ANTICUERPOS ANTI LA (ANTI - SSB)', 'name_report' => 'ANTI-SSB', 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ARNP', 'name' => 'ANTICUERPOS ANTI RNP', 'name_report' => 'ANTI-RNP', 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ANTIRO', 'name' => 'ANTICUERPOS ANTI-RO (ANTI-SSA)', 'name_report' => 'ANTI-SSA', 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ANTISM', 'name' => 'ANTICUERPOS ANTI SM (ANTI SMITH)', 'name_report' => 'ANTI-SM', 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'LKM1', 'name' => 'ANTICUERPOS ANTIMICROSOMALES HÍGADO RIÑON (LKM1)', 'name_report' => 'LKM1', 'hour_process' => 96],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ANA', 'name' => 'ANTICUERPOS ANTINUCLEARES ANA', 'name_report' => 'ANA', 'hour_process' => 72],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ACENDA', 'name' => 'ANTIENDOMISIO IgA', 'name_report' => 'ENDOMISIO IGA', 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ACENDM', 'name' => 'ANTIENDOMISIO IgM', 'name_report' => 'ENDOMISIO IGM', 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ASTO', 'name' => 'ANTIESTREPTOLISINA (ASTO)', 'name_report' => 'ASTO', 'hour_process' => 4],
                ['samples' => ['Suero (Rojo)'], 'code' => 'CEA', 'name' => 'ANTIGENO CARCINOEMBRIONARIO (CEA)', 'name_report' => 'CEA', 'hour_process' => 24],
                ['samples' => ['Secreción Faríngea'], 'code' => 'STREPA', 'name' => 'ANTIGENO DE ESTREPTOCOCO GRUPO A (STREP A TEST)', 'name_report' => 'STREP A', 'hour_process' => 24],
                ['samples' => ['Materia Fecal'], 'code' => 'AGIAR', 'name' => 'GIARDIA ANTÍGENOS EN HECES POR MÉTODO INMUNOLÓGICO', 'name_report' => 'GIARIDA', 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'PSA', 'name' => 'ANTIGENO PROSTATICO ESPECIFICO (PSA TOTAL)', 'name_report' => 'PSA', 'hour_process' => 1],
                ['samples' => ['Suero (Rojo)'], 'code' => 'FPSA', 'name' => 'ANTÍGENO PROSTÁTICO LIBRE (FPSA)', 'name_report' => 'FPSA', 'hour_process' => 5],
                ['samples' => ['Suero (Rojo)'], 'code' => 'EBVNAG', 'name' => 'EPSTEIN BARR ANTÍGENOS NUCLEARES IGG (EBNA IGG)', 'name_report' => null, 'hour_process' => 4],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ANGLIA', 'name' => 'ANTI GLIADINA IgA', 'name_report' => 'A. GLIADINA IGA', 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ANGLIG', 'name' => 'ANTI GLIADINA IgG', 'name_report' => 'A. GLIADINA IGG', 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'AMA', 'name' => 'ANTIMITOCONDRIALES (AMA)', 'name_report' => 'AMA', 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ATSH', 'name' => 'ANTIRECEPTOR TSH', 'name_report' => 'ATSH', 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'TRANSA', 'name' => 'TRANSGLUTAMINASA TISULAR IgA', 'name_report' => 'A. TRANSGL. IGA', 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'TRANSG', 'name' => 'TRANSGLUTAMINASA TISULAR IgG', 'name_report' => 'A. TRANSGL. IGG', 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'APOA', 'name' => 'APOLIPOPROTEINA A', 'name_report' => 'APO-A', 'hour_process' => 72],
                ['samples' => ['Suero (Rojo)'], 'code' => 'APOB', 'name' => 'APOLIPOPROTEÍNA B', 'name_report' => 'APO-B', 'hour_process' => 72],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ASCAG', 'name' => 'SACCHARAMYCES CEREVISIAE (ASCA IgG)', 'name_report' => 'ASCA IGG', 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ASCAM', 'name' => 'SACCHARAMYCES CEREVISIAE (ASCA IgM)', 'name_report' => 'ASCA IGM', 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'TGO', 'name' => 'ASPARTATO AMINOTRANSFERASA GOT (AST)', 'name_report' => 'TGO', 'hour_process' => 3],
                ['samples' => ['Suero (Rojo)'], 'code' => 'AHBE', 'name' => 'HEPATITIS B ANTICUERPOS CONTRA ANTÍGENO E (Anti-HBe)', 'name_report' => 'ANTI-HBE', 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'JO1', 'name' => 'AC. ANTI-JO-1', 'name_report' => 'ANTI JO1', 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'PAPERA', 'name' => 'ANTI PAPERAS IGG', 'name_report' => 'PAPERAS IGG', 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'SCL70', 'name' => 'ANTI SCL70', 'name_report' => 'ANTI SCL70', 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'HDL', 'name' => 'COLESTEROL HDL', 'name_report' => 'HDL', 'hour_process' => 5],
                ['samples' => ['Suero (Rojo)'], 'code' => 'LDL', 'name' => 'COLESTEROL LDL', 'name_report' => 'LDL', 'hour_process' => 5],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'BH', 'name' => 'BIOMETRÍA HEMÁTICA', 'name_report' => 'BH', 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'GLU', 'name' => 'GLUCOSA', 'name_report' => 'GLU', 'hour_process' => 5],
                ['samples' => ['Suero (Rojo)'], 'code' => 'HER2IM', 'name' => 'HERPES SIMPLE TIPO 2 (IgM)', 'name_report' => 'HER2IGM', 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'HER2IG', 'name' => 'HERPES SIMPLE TIPO 2 (IgG)', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'VDRL', 'name' => 'VDRL', 'name_report' => null, 'hour_process' => 1],
                ['samples' => ['Suero (Rojo)'], 'code' => 'K', 'name' => 'POTASIO', 'name_report' => null, 'hour_process' => 2],
                ['samples' => ['Suero (Rojo)'], 'code' => 'NA', 'name' => 'SODIO EN SUERO', 'name_report' => null, 'hour_process' => 2],
                ['samples' => ['Suero (Rojo)'], 'code' => 'TOXOIM', 'name' => 'TOXOPLASMA IgM', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Materia Fecal'], 'code' => 'COPRO', 'name' => 'COPROPARASITARIO', 'name_report' => null, 'hour_process' => 1],
                ['samples' => ['Suero (Rojo)'], 'code' => 'TSH', 'name' => 'HORMONA ESTIMULANTE DEL TIROIDES (TSH)', 'name_report' => 'TSH', 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'BILIN', 'name' => 'BILIRRUBINA', 'name_report' => null, 'hour_process' => 3],
                ['samples' => ['Suero (Rojo)'], 'code' => 'GGT', 'name' => 'GAMMA GT', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'COLINE', 'name' => 'COLINESTERASA ERITROCITARIA', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'CMVIM', 'name' => 'CITOMEGALOVIRUS (CMV) IGM', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'HER1IM', 'name' => 'HERPES SIMPLE TIPO 1 (IGM)', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'HPYLOG', 'name' => 'HELICOBACTER PYLORI ANTICUERPOS IGG CUANTITATIVO', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'TOXOIG', 'name' => 'TOXOPLASMA IgG', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'BUN', 'name' => 'BUN NITRÓGENO URÉICO EN SANGRE', 'name_report' => null, 'hour_process' => 4],
                ['samples' => ['Suero (Rojo)'], 'code' => 'HER1IG', 'name' => 'HERPES SIMPLE TIPO 1 (IGG)', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Sangre Citrato (Celeste)'], 'code' => 'TP', 'name' => 'TIEMPO DE PROTROMBINA TP', 'name_report' => null, 'hour_process' => 1],
                ['samples' => ['Suero (Rojo)'], 'code' => 'RUBIM', 'name' => 'RUBEOLA IGM CUANTITATIVA', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Sangre Citrato (Celeste)'], 'code' => 'TTP', 'name' => 'TIEMPO PARCIAL DE TROMBOPLASTINA TTP', 'name_report' => null, 'hour_process' => 2],
                ['samples' => ['Suero (Rojo)'], 'code' => 'CL', 'name' => 'CLORO', 'name_report' => null, 'hour_process' => 2],
                ['samples' => ['Suero (Rojo)'], 'code' => 'HIV', 'name' => 'HIV 1 + 2', 'name_report' => null, 'hour_process' => 4],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'PLAQ', 'name' => 'RECUENTO DE PLAQUETAS', 'name_report' => null, 'hour_process' => 1],
                ['samples' => ['Suero (Rojo)'], 'code' => 'RUBIG', 'name' => 'RUBEOLA IGG CUANTITATIVA', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'CMVIG', 'name' => 'CITOMEGALOVIRUS (CMV) IGG', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'HCGCNT', 'name' => 'HCG BETA CUANTITATIVO', 'name_report' => null, 'hour_process' => 1],
                ['samples' => ['Suero (Rojo)'], 'code' => 'TG', 'name' => 'TIROGLOBULINA', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ABIL', 'name' => 'ÁCIDOS BILIARES', 'name_report' => null, 'hour_process' => 2],
                ['samples' => ['Suero (Rojo)'], 'code' => 'HBSAC', 'name' => 'HEPATITIS B ANTICUERPOS DE SUPERFICIE (HBsAc)', 'name_report' => 'ANTI-HBS', 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'HBSAG', 'name' => 'HEPATITIS B ANTIGENO AUSTRALIA DE SUPERFICIE (HBsAg)', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'CA', 'name' => 'CALCIO', 'name_report' => null, 'hour_process' => 5],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'GRUPO', 'name' => 'TIPIFICACION SANGUINEA RH (D)', 'name_report' => null, 'hour_process' => 1],
                ['samples' => ['Suero (Rojo)'], 'code' => 'PROTO', 'name' => 'PROTEINAS TOTALES EN SUERO', 'name_report' => null, 'hour_process' => 5],
                ['samples' => ['Suero (Rojo)'], 'code' => 'CA125', 'name' => 'MARCADOR TUMORAL CA 125', 'name_report' => null, 'hour_process' => 1],
                ['samples' => ['Suero (Rojo)'], 'code' => 'CHLAMM', 'name' => 'CHLAMYDIA TRACHOMATIS IGM', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'T4', 'name' => 'T4 TIROXINA TOTAL', 'name_report' => null, 'hour_process' => 2],
                ['samples' => ['Suero (Rojo)'], 'code' => 'DHEAS', 'name' => 'DHEAS', 'name_report' => null, 'hour_process' => 4],
                ['samples' => ['Suero (Rojo)'], 'code' => 'TESTO', 'name' => 'TESTOSTERONA TOTAL', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'CA+', 'name' => 'CALCIO IÓNICO', 'name_report' => null, 'hour_process' => 2],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'HBGLI', 'name' => 'HEMOGLOBINA GLICOSILADA TOTAL HBA1C', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'FERRI', 'name' => 'FERRITINA', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'FRUCT', 'name' => 'FRUCTOSAMINA', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'HPYLOM', 'name' => 'HELICOBACTER PYLORI ANTICUERPOS IGM CUANTITATIVO', 'name_report' => null, 'hour_process' => 72],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'PTH', 'name' => 'PARATOHORMONA', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'FE', 'name' => 'HIERRO SÉRICO', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'FOSFOR', 'name' => 'FÓSFORO EN SUERO', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Orina'], 'code' => 'PROTEI', 'name' => 'PROTEINURIA EN ORINA DE 24 HORAS', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'IGE', 'name' => 'INMUNOGLOBULINA E (IGE)', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Orina'], 'code' => 'MICROA', 'name' => 'MICROALBUMINURIA EN ORINA PARCIAL (CUALITATIVA)', 'name_report' => null, 'hour_process' => 2],
                ['samples' => ['Suero (Rojo)'], 'code' => 'FT3', 'name' => 'T3 LIBRE', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'T3', 'name' => 'T3 TOTAL', 'name_report' => null, 'hour_process' => 2],
                ['samples' => ['Suero (Rojo)'], 'code' => 'EMB', 'name' => 'HCG BETA CUALITATIVO (TEST DE EMBARAZO EN SANGRE)', 'name_report' => null, 'hour_process' => 1],
                ['samples' => ['Suero (Rojo)'], 'code' => 'VLDL', 'name' => 'COLESTEROL VLDL', 'name_report' => null, 'hour_process' => 1],
                ['samples' => ['Suero (Rojo)'], 'code' => 'FALK', 'name' => 'FOSFATASA ALCALINA', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'AMIL', 'name' => 'AMILASA', 'name_report' => null, 'hour_process' => 4],
                ['samples' => ['Suero (Rojo)'], 'code' => 'CA153', 'name' => 'MARCADOR TUMORAL CA 15-3', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'LIPASA', 'name' => 'LIPASA', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'CA199', 'name' => 'MARCADOR TUMORAL CA 19-9', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'CORTAM', 'name' => 'CORTISOL AM', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'C3', 'name' => 'COMPLEMENTO C3', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'CK', 'name' => 'CREATIN KINASA TOTAL (CK/CPK)', 'name_report' => null, 'hour_process' => 2],
                ['samples' => ['Suero (Rojo)'], 'code' => 'CHLAMG', 'name' => 'CHLAMYDIA TRACHOMATIS IGG', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'MG', 'name' => 'MAGNESIO EN SUERO', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'PROG', 'name' => 'PROGESTERONA', 'name_report' => null, 'hour_process' => 4],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'RETI', 'name' => 'RETICULOCITOS', 'name_report' => null, 'hour_process' => 2],
                ['samples' => ['Suero PP (Rojo)', 'Suero (Rojo)'], 'code' => 'GLU2PP', 'name' => 'GLUCOSA POSTPRANDIAL 2H', 'name_report' => null, 'hour_process' => 5],
                ['samples' => ['Materia Fecal'], 'code' => 'IPMN', 'name' => 'INVESTIGACIÓN DE POLIMORFONUCLEARES (CITOLOGIA MOCO FECAL)', 'name_report' => null, 'hour_process' => 1],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'HB', 'name' => 'HEMOGLOBINA', 'name_report' => null, 'hour_process' => 2],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'HCTO', 'name' => 'HEMATOCRITO', 'name_report' => null, 'hour_process' => 1],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'VSG', 'name' => 'ERITROSEDIMENTACIÓN', 'name_report' => null, 'hour_process' => 1],
                ['samples' => ['Suero (Rojo)'], 'code' => 'COOMIN', 'name' => 'COOMBS INDIRECTO', 'name_report' => null, 'hour_process' => 1],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'COOMDI', 'name' => 'COOMBS DIRECTO', 'name_report' => null, 'hour_process' => 2],
                ['samples' => ['Suero (Rojo)'], 'code' => 'CRUZ', 'name' => 'PRUEBAS CRUZADAS', 'name_report' => null, 'hour_process' => 2],
                ['samples' => ['Suero (Rojo)'], 'code' => 'HPYLOA', 'name' => 'HELICOBACTER PYLORI ANTICUERPOS IgA CUANTITATIVO', 'name_report' => null, 'hour_process' => 72],
                ['samples' => ['Suero (Rojo)'], 'code' => 'AHBCM', 'name' => 'HEPATITIS B ANTICORE IGM (Anti-HBc IgM)', 'name_report' => 'HBCM-IGM', 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'AFP', 'name' => 'ALFAFETOPROTEINA', 'name_report' => null, 'hour_process' => 120],
                ['samples' => ['Suero (Rojo)'], 'code' => 'E2', 'name' => 'ESTRADIOL', 'name_report' => null, 'hour_process' => 4],
                ['samples' => ['Suero (Rojo)'], 'code' => 'HGH', 'name' => 'HORMONA DE CRECIMIENTO BASAL (HGH)', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'HBCTOT', 'name' => 'HEPATITIS B ANTICORE ANTICUERPOS TOTALES (Anti-HBc)', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'HAVIGM', 'name' => 'HEPATITIS A (HAV) ANTICUERPOS IgM', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'FSH', 'name' => 'HORMONA FOLÍCULO ESTIMULANTE (FSH)', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Sangre Citrato (Celeste)'], 'code' => 'TT', 'name' => 'TIEMPO DE TROMBINA', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Materia Fecal'], 'code' => 'HPYHEC', 'name' => 'HELICOBACTER PYLORI EN HECES', 'name_report' => null, 'hour_process' => 2],
                ['samples' => ['Suero (Rojo)'], 'code' => 'PRL', 'name' => 'PROLACTINA', 'name_report' => null, 'hour_process' => 4],
                ['samples' => ['Suero (Rojo)'], 'code' => 'HAVIGG', 'name' => 'HEPATITIS A (HAV) ANTICUERPOS IgG', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'LDH', 'name' => 'DESHIDROGENASA LACTICA LDH', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'U', 'name' => 'UREA', 'name_report' => 'U', 'hour_process' => 5],
                ['samples' => ['Suero (Rojo)'], 'code' => 'CRE', 'name' => 'CREATININA', 'name_report' => 'CRE', 'hour_process' => 5],
                ['samples' => ['Suero (Rojo)'], 'code' => 'DENGMG', 'name' => 'DENGUE IgM + IgG PRUEBA RÁPIDA', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'DENGIG', 'name' => 'ANTI DENGUE IGG', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'HEMATO', 'name' => 'HEMATOZOARIO', 'name_report' => null, 'hour_process' => 3],
                ['samples' => ['Suero (Rojo)'], 'code' => 'FR', 'name' => 'FACTOR REUMATOIDEO (LATEX)', 'name_report' => null, 'hour_process' => 2],
                ['samples' => ['Suero (Rojo)'], 'code' => 'PCRCLT', 'name' => 'PCR PROTEINA C REACTIVA CUALITATIVA', 'name_report' => null, 'hour_process' => 2],
                ['samples' => ['Suero (Rojo)'], 'code' => 'PCRUL', 'name' => 'PCR ULTRASENSIBLE', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Materia Fecal'], 'code' => 'SAHEC', 'name' => 'SANGRE OCULTA EN HECES', 'name_report' => null, 'hour_process' => 1],
                ['samples' => ['Materia Fecal'], 'code' => 'ROTA', 'name' => 'ROTAVIRUS EN MATERIA FECAL', 'name_report' => null, 'hour_process' => 1],
                ['samples' => ['Orina'], 'code' => 'GRAMOR', 'name' => 'GRAM (GOTA FRESCA) ORINA', 'name_report' => null, 'hour_process' => 2],
                ['samples' => ['Muestras Varias'], 'code' => 'GRAMSE', 'name' => 'GRAM Y FRESCO SECRECION', 'name_report' => null, 'hour_process' => 2],
                ['samples' => ['Suero (Rojo)'], 'code' => 'CHLAMA', 'name' => 'CHLAMYDIA TRACHOMATIS IGA (DIRECTA)', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Líquido Amniótico'], 'code' => 'CRISTA', 'name' => 'CRISTALOGRAFÍA', 'name_report' => null, 'hour_process' => 4],
                ['samples' => ['Muestras Varias'], 'code' => 'LEISH', 'name' => 'LEISHMANIA', 'name_report' => null, 'hour_process' => 3],
                ['samples' => ['Muestras Varias'], 'code' => 'PARAGO', 'name' => 'PARAGONIMUS', 'name_report' => null, 'hour_process' => 3],
                ['samples' => ['Muestras Varias'], 'code' => 'CULTI', 'name' => 'CULTIVO Y ANTIBIOGRAMA MUESTRAS VARIAS', 'name_report' => null, 'hour_process' => 72],
                ['samples' => ['Suero (Rojo)'], 'code' => 'B12', 'name' => 'VITAMINA B12', 'name_report' => null, 'hour_process' => 8],
                ['samples' => ['Suero (Rojo)'], 'code' => 'INSUL', 'name' => 'INSULINA BASAL', 'name_report' => null, 'hour_process' => 3],
                ['samples' => ['Suero (Rojo)'], 'code' => 'C4', 'name' => 'COMPLEMENTO C4', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'CORTPM', 'name' => 'CORTISOL PM', 'name_report' => null, 'hour_process' => 3],
                ['samples' => ['Suero (Rojo)'], 'code' => 'TUBERC', 'name' => 'ANTICUERPOS CONTRA TUBERCULOSIS', 'name_report' => null, 'hour_process' => 3],
                ['samples' => ['Suero (Rojo)'], 'code' => 'EBVNAM', 'name' => 'EPSTEIN BARR ANTÍGENOS NUCLEARES IGM (EBNA IGM)', 'name_report' => null, 'hour_process' => 4],
                ['samples' => ['Suero (Rojo)'], 'code' => 'PEPC', 'name' => 'PÉPTIDO C', 'name_report' => null, 'hour_process' => 3],
                ['samples' => ['Sangre Citrato (Celeste)'], 'code' => 'FIBRI', 'name' => 'FIBRINÓGENO', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'LH', 'name' => 'HORMONA LUTEINIZANTE (LH)', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'TRANSF', 'name' => 'TRANSFERRINA', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Materia Fecal'], 'code' => 'COPRO2', 'name' => 'COPROPARASITARIO DÍA 2', 'name_report' => null, 'hour_process' => 1],
                ['samples' => ['Suero (Rojo)'], 'code' => 'COLSE', 'name' => 'COLINESTERASA SÉRICA', 'name_report' => null, 'hour_process' => 3],
                ['samples' => ['Materia Fecal'], 'code' => 'COPRO3', 'name' => 'COPROPARASITARIO DÍA 3', 'name_report' => null, 'hour_process' => 1],
                ['samples' => ['Suero (Rojo)'], 'code' => 'GLOBU', 'name' => 'GLOBULINA', 'name_report' => null, 'hour_process' => 1],
                ['samples' => ['Suero (Rojo)'], 'code' => 'IGG', 'name' => 'INMUNOGLOBULINA G (IGG)', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => '25OH', 'name' => 'VITAMINA D 25 HIDROXI', 'name_report' => null, 'hour_process' => 1],
                ['samples' => ['Suero (Rojo)'], 'code' => 'IGM', 'name' => 'INMUNOGLOBULINA M (IGM)', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'CKMB', 'name' => 'CPK FRACCIÓN MB', 'name_report' => null, 'hour_process' => 3],
                ['samples' => ['Suero (Rojo)'], 'code' => 'IGA', 'name' => 'INMUNOGLOBULINA A (IGA)', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'FTAABS', 'name' => 'TREPONEMA PALLIDUM PRUEBA DE CONFIRMACIÓN SÍFILIS(FTA-ABS)', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'ACTH', 'name' => 'HORMONA ADRENOCORTICOTROPICA (ACTH)', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'IGF1', 'name' => 'IGF1 (SOMATOMEDINA C)', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'HE4', 'name' => 'HE4', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'FAT', 'name' => 'FOSFATASA ÁCIDA TOTAL', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Paciente'], 'code' => 'PAP', 'name' => 'CITOLOGIA CERVICO - VAGINAL (PAP)', 'name_report' => null, 'hour_process' => 72],
                ['samples' => ['Sangre Citrato (Celeste)'], 'code' => 'DIMERO', 'name' => 'DÍMERO D', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Materia Fecal'], 'code' => 'CLINI', 'name' => 'CLINITEST (AZUCARES REDUCTORES) EN HECES', 'name_report' => null, 'hour_process' => 3],
                ['samples' => ['Orina'], 'code' => 'NAO', 'name' => 'SODIO EN ORINA', 'name_report' => null, 'hour_process' => 3],
                ['samples' => ['Orina'], 'code' => 'KO', 'name' => 'POTASIO EN ORINA', 'name_report' => null, 'hour_process' => 3],
                ['samples' => ['Orina'], 'code' => 'CLO', 'name' => 'CLORO EN ORINA', 'name_report' => null, 'hour_process' => 3],
                ['samples' => ['Suero (Rojo)'], 'code' => 'PCT', 'name' => 'PROCALCITONINA', 'name_report' => null, 'hour_process' => 3],
                ['samples' => ['Semen'], 'code' => 'ESPERM', 'name' => 'ESPERMATOGRAMA', 'name_report' => null, 'hour_process' => 5],
                ['samples' => ['Suero (Rojo)'], 'code' => 'TROPON', 'name' => 'TROPONINA', 'name_report' => null, 'hour_process' => 5],
                ['samples' => ['Suero (Rojo)'], 'code' => 'FAP', 'name' => 'FOSFATASA ÁCIDA PROSTÁTICA', 'name_report' => null, 'hour_process' => 3],
                ['samples' => ['Suero (Rojo)'], 'code' => 'LI', 'name' => 'LITIO EN SUERO', 'name_report' => null, 'hour_process' => 4],
                ['samples' => ['Suero (Rojo)'], 'code' => 'TESTLI', 'name' => 'TESTOSTERONA LIBRE', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'CHAGIG', 'name' => 'TRYPANOZOMA CRUZI (CHAGAS) ANTICUERPOS IgG', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'ELECHB', 'name' => 'ELECTROFORESIS DE HEMOGLOBINA', 'name_report' => null, 'hour_process' => 240],
                ['samples' => ['Suero (Rojo)'], 'code' => 'FRAOSM', 'name' => 'FRAGILIDAD OSMOTICA', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Sangre Total Heparinizada (Verde)'], 'code' => 'METHB', 'name' => 'METAHEMOGLOBINA', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Sangre Total Heparinizada (Verde)'], 'code' => 'CARBOX', 'name' => 'CARBOXIHEMOGLOBINA', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'PALUDI', 'name' => 'HEMATOZOARIOS (INVESTIGACIÓN DE MALARIA - PALUDISMO)', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Sangre Total Heparinizada (Verde)'], 'code' => 'CARIO', 'name' => 'CARIOTIPO EN SANGRE', 'name_report' => null, 'hour_process' => 480],
                ['samples' => ['Sangre Total Heparinizada (Verde)'], 'code' => 'CARIOM', 'name' => 'CARIOTIPO MEDULA OSEA', 'name_report' => null, 'hour_process' => 480],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'INVDRE', 'name' => 'INVESTIGACION DE DREPANOCITOS', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'FCVLEY', 'name' => 'FACTOR V DE LEYDEN CONFIRMATORIO POR PCR', 'name_report' => null, 'hour_process' => 120],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'PROTRO', 'name' => 'ESTUDIO MOLECULAR DEL GEN DE LA PROTROMBINA', 'name_report' => null, 'hour_process' => 120],
                ['samples' => ['Sangre Citrato (Celeste)'], 'code' => 'FACII', 'name' => 'FACTOR II  ( ACTIVIDAD DE LA PROTROMBINA)', 'name_report' => null, 'hour_process' => 192],
                ['samples' => ['Sangre Citrato (Celeste)'], 'code' => 'FACV', 'name' => 'FACTOR V  (ACTIVIDAD)', 'name_report' => null, 'hour_process' => 192],
                ['samples' => ['Sangre Citrato (Celeste)'], 'code' => 'FACVII', 'name' => 'FACTOR VII', 'name_report' => null, 'hour_process' => 192],
                ['samples' => ['Sangre Citrato (Celeste)'], 'code' => 'FAVIII', 'name' => 'FACTOR VIII', 'name_report' => null, 'hour_process' => 240],
                ['samples' => ['Sangre Citrato (Celeste)'], 'code' => 'FACIX', 'name' => 'FACTOR IX', 'name_report' => null, 'hour_process' => 192],
                ['samples' => ['Sangre Citrato (Celeste)'], 'code' => 'FACTX', 'name' => 'FACTOR X', 'name_report' => null, 'hour_process' => 192],
                ['samples' => ['Sangre Citrato (Celeste)'], 'code' => 'ANTITR', 'name' => 'ANTITROMBINA III', 'name_report' => null, 'hour_process' => 192],
                ['samples' => ['Sangre Citrato (Celeste)'], 'code' => 'PROTC', 'name' => 'PROTEINA C ( % ACTIVIDAD)', 'name_report' => null, 'hour_process' => 192],
                ['samples' => ['Sangre Citrato (Celeste)'], 'code' => 'PROTS', 'name' => 'PROTEINA S ( % DE ACTIVIDAD FUNCIONAL)', 'name_report' => null, 'hour_process' => 192],
                ['samples' => ['Orina'], 'code' => 'DEPCRE', 'name' => 'DEPURACION DE CREATININA EN ORINA DE 24 HORAS', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Orina'], 'code' => 'MIALBC', 'name' => 'MICROALBUMINURIA CUANTITATIVA', 'name_report' => null, 'hour_process' => 5],
                ['samples' => ['Orina'], 'code' => 'BENCEJ', 'name' => 'PROTEINA DE BENCE JONES', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Muestras Varias'], 'code' => 'CALUR', 'name' => 'CALCULOS URINARIOS (ANALISIS QUIMICO)', 'name_report' => null, 'hour_process' => 72],
                ['samples' => ['Orina'], 'code' => 'ELECPR', 'name' => 'ELECTROFORESIS DE PROTEINAS EN ORINA DE 24 HORAS', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Orina'], 'code' => 'PROTOR', 'name' => 'PROTEÍNAS EN ORINA', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Orina'], 'code' => 'AZUOR', 'name' => 'AZUCARES REDUCTORES EN ORINA', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Materia Fecal'], 'code' => 'SUDAN', 'name' => 'SUDAN III (INVESTIGACION DE GRASAS EN HECES)', 'name_report' => null, 'hour_process' => 3],
                ['samples' => ['Materia Fecal'], 'code' => 'COPROC', 'name' => 'COPROPARASITARIO POR CONCENTRACION', 'name_report' => null, 'hour_process' => 5],
                ['samples' => ['Muestras Varias'], 'code' => 'INVOX', 'name' => 'INVESTIGACION DE OXIUROS', 'name_report' => null, 'hour_process' => 4],
                ['samples' => ['Muestras Varias'], 'code' => 'ZIEHLB', 'name' => 'ZIEHL- BAAR', 'name_report' => null, 'hour_process' => 4],
                ['samples' => ['Muestras Varias'], 'code' => 'TINCHI', 'name' => 'TINTA CHINA', 'name_report' => null, 'hour_process' => 3],
                ['samples' => ['Materia Fecal Cultivo'], 'code' => 'CULTCO', 'name' => 'COPROCULTIVO', 'name_report' => null, 'hour_process' => 3],
                ['samples' => ['Muestras Varias'], 'code' => 'CULSV', 'name' => 'CULTIVO DE SECRECION VAGINAL', 'name_report' => null, 'hour_process' => 72],
                ['samples' => ['Materia Fecal'], 'code' => 'CLOSTR', 'name' => 'CLOSTRIDIUM DIFFICILE TOXINA A', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Materia Fecal'], 'code' => 'CLOSTO', 'name' => 'CLOSTRIDIUM DIFICILE TOXINA A/B', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Muestras Varias'], 'code' => 'CULHON', 'name' => 'CULTIVO PARA HONGOS', 'name_report' => null, 'hour_process' => 240],
                ['samples' => ['Muestras Varias'], 'code' => 'GRAM', 'name' => 'GRAM TINCION', 'name_report' => null, 'hour_process' => 4],
                ['samples' => ['Muestras Varias'], 'code' => 'FRESCO', 'name' => 'GRAM Y FRESCO DE LIQUIDO', 'name_report' => null, 'hour_process' => 4],
                ['samples' => ['Sangre Total EDTA2 (Lila)'], 'code' => 'HEMOCU', 'name' => 'HEMOCULTIVO', 'name_report' => null, 'hour_process' => 168],
                ['samples' => ['Muestras Varias'], 'code' => 'KOH', 'name' => 'INVESTIGACION DIRECTA DE HONGOS (KOH)', 'name_report' => null, 'hour_process' => 3],
                ['samples' => ['Muestras Varias'], 'code' => 'FUNLEV', 'name' => 'FUNGIGRAMA PARA LEVADURAS', 'name_report' => null, 'hour_process' => 72],
                ['samples' => ['Muestras Varias'], 'code' => 'CALVES', 'name' => 'CALCULO VESICULAR', 'name_report' => null, 'hour_process' => 72],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ALCHO', 'name' => 'ALCOHOL ETILICO EN SANGRE', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Orina'], 'code' => 'AMILOR', 'name' => 'AMILASA EN ORINA', 'name_report' => null, 'hour_process' => 5],
                ['samples' => ['Orina'], 'code' => 'CAOR', 'name' => 'CALCIO EN ORINA', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Orina'], 'code' => 'CREAOR', 'name' => 'CREATININA EN ORINA', 'name_report' => null, 'hour_process' => 5],
                ['samples' => ['Orina'], 'code' => 'FOSOR', 'name' => 'FÓSFORO EN ORINA', 'name_report' => null, 'hour_process' => 5],
                ['samples' => ['Suero (Rojo)'], 'code' => 'OSMOSE', 'name' => 'OSMOLARIDAD SERICA', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'OSMURI', 'name' => 'OSMOLARIDAD URINARIA', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero 1H (Rojo)', 'Suero 2H (Rojo)', 'Suero (Rojo)'], 'code' => 'CURV2H', 'name' => 'CURVA DE GLUCOSA 2 HORAS', 'name_report' => null, 'hour_process' => 5],
                ['samples' => ['Suero 1H (Rojo)', 'Suero 2H (Rojo)', 'Suero 3H (Rojo)', 'Suero (Rojo)'], 'code' => 'CURV3H', 'name' => 'CURVA DE GLUCOSA 3 HORAS', 'name_report' => null, 'hour_process' => 7],
                ['samples' => ['Suero (Rojo)'], 'code' => 'UREA24', 'name' => 'UREA EN ORINA DE 24 HORAS', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'EVERO', 'name' => 'EVEROLIMUS (CERTICAN)', 'name_report' => null, 'hour_process' => 480],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ALDOS', 'name' => 'ALDOSTERONA', 'name_report' => null, 'hour_process' => 120],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ERITRO', 'name' => 'ERITROPOYETINA', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Lavado Bronquial'], 'code' => 'ADENOR', 'name' => 'ADENOVIRUS RESPIRATORIO', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'SEROAM', 'name' => 'SEROMOEBA (ANTICUERPOS ANTI AMOEBA HISTOLITICA)', 'name_report' => null, 'hour_process' => 120],
                ['samples' => ['Suero (Rojo)'], 'code' => 'CHAGAS', 'name' => 'TRYPANOZOMA CRUZI (CHAGAS TOTALES) ANTICUERPOS (IGG + IGM)', 'name_report' => null, 'hour_process' => 120],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'TOXODN', 'name' => 'TOXOPLASMA DNA DETECTOR', 'name_report' => null, 'hour_process' => 96],
                ['samples' => ['Suero (Rojo)'], 'code' => 'VARIM', 'name' => 'VARICELA ZOSTER; ANTICUERPOS IgM', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'VARIG', 'name' => 'VARICELA ZOSTER; ANTICUERPOS IgG', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Materia Fecal'], 'code' => 'CRIPTO', 'name' => 'CRIPTOSPORIDIUM', 'name_report' => null, 'hour_process' => 4],
                ['samples' => ['Plasma (Verde)', 'Liquido Cefalorraquideo', 'Hisopado Nasofaringeo'], 'code' => 'CMV', 'name' => 'CITOMEGALOVIRUS POR RT-PCR', 'name_report' => null, 'hour_process' => 72],
                ['samples' => ['Suero (Rojo)'], 'code' => 'CMVAVI', 'name' => 'CITOMEGALOVIRUS IgG AVIDEZ', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'HAVTO', 'name' => 'HEPATITIS A (HAV) ANTICUERPOS TOTALES PRUEBA RÁPIDA', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'HBEAG', 'name' => 'HEPATITIS B ANTIGENO E (HBeAg)', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'AHCV', 'name' => 'HEPATITIS C ANTICUERPOS TOTALES (HCV)', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'HER1-2', 'name' => 'HERPES 1 Y 2 ADN/PCR', 'name_report' => 'HER 1-2', 'hour_process' => 96],
                ['samples' => ['Suero (Rojo)'], 'code' => 'AHIV24', 'name' => 'ANTI HIV 1 Y 2 ANTÍGENO P24', 'name_report' => 'HIVCOMBI', 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'MONOTE', 'name' => 'MONONUCLEOSIS ANTICUERPOS HETEROFILOS (MONO TEST)', 'name_report' => 'MONOTEST', 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'SIFIM', 'name' => 'TREPONEMA PALLIDUM IgM (SIFILIS IgM)', 'name_report' => null, 'hour_process' => 120],
                ['samples' => ['Suero (Rojo)'], 'code' => 'INVTRE', 'name' => 'INVESTIGACIÓN TREPONEMA PALLIDUM', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'SIFTOT', 'name' => 'TREPONEMA PALLIDUM ANTICUERPOS IgG/IgM (SIFILIS TOTALES)', 'name_report' => null, 'hour_process' => 72],
                ['samples' => ['Liquido Cefalorraquideo'], 'code' => 'SIFFTA', 'name' => 'TREPONEMA PALLIDUM (FTA) EN LCR, ANTICUERPOS', 'name_report' => 'FTA-LCR', 'hour_process' => 240],
                ['samples' => ['Suero (Rojo)'], 'code' => 'TOXOAV', 'name' => 'TOXOPLASMA GONDII ESTUDIO DE AVIDEZ', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'INFLAB', 'name' => 'VIRUS INFLUENZA A Y B (ANTIGENO)', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'VSINCI', 'name' => 'VIRUS SINCITAL RESPIRATORIO (ANTÍGENO)', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'LEGIG', 'name' => 'LEGIONELLA PNEUMONIAE IgG', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'LEGIM', 'name' => 'LEGIONELLA PNEUMONIAE IgM', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ALEG', 'name' => 'LEGIONELLA ANTIGENO', 'name_report' => null, 'hour_process' => 192],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ALEPT', 'name' => 'LEPTOSPIRA ANTICUERPOS TOTALES (IgG/IgM)', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ATUBER', 'name' => 'ANTI TUBERCULOSIS SERICA (IgG)', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'CHLNA', 'name' => 'CHLAMYDIA PNEUMONIAE IgA', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'CHLNM', 'name' => 'CHLAMYDIA PNEUMONIAE IgM', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'CHLNG', 'name' => 'CHLAMYDIA PNEUMONIAE IgG', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'MYCOM', 'name' => 'ANTICUERPOS IgM ANTI MYCOPLASMA PNEUMONIAE EN SUERO', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'MYCOG', 'name' => 'ANTICUERPOS IgG ANTI MYCOPLASMA PNEUMONIAE EN SUERO', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'MYCOA', 'name' => 'ANTICUERPOS IgA ANTI MYCOPLASMA PNEUMONIAE EN SUERO', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'HIVCAR', 'name' => 'HIV CARGA VIRAL', 'name_report' => null, 'hour_process' => 240],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'CD4CD8', 'name' => 'RECUENTO ABSOLUTO DE CD4/CD8', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'RESHIV', 'name' => 'RESISTENCIA HIV (GENOTIPO RETROTRANSCRIPTASA Y PROTEASA)', 'name_report' => null, 'hour_process' => 360],
                ['samples' => ['Cepillado Cervico-vaginal'], 'code' => 'HPVALT', 'name' => 'HPV DE ALTO RIESGO +16  +18', 'name_report' => null, 'hour_process' => 168],
                ['samples' => ['Cepillado Cervico-vaginal'], 'code' => 'HPVPAP', 'name' => 'HPV DE ALTO RIESGO  CEPAS 16  +18/ PAPANILCOLAU', 'name_report' => null, 'hour_process' => 72],
                ['samples' => ['Cepillado Cervico-vaginal'], 'code' => 'HPVGEN', 'name' => 'GENOTIPIFICACION HPV 28 GENOTIPOS', 'name_report' => null, 'hour_process' => 504],
                ['samples' => ['Suero (Rojo)'], 'code' => 'PARVG', 'name' => 'PARVOVIRUS B19 IgG', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'PARVM', 'name' => 'PARVOVIRUS B19 IgM', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Sangre Total Heparinizada (Verde)'], 'code' => 'QUANTB', 'name' => 'QUANTIFERON TB', 'name_report' => null, 'hour_process' => 240],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ALEPTG', 'name' => 'LEPTOSPIRA ANTICUERPOS IgG', 'name_report' => null, 'hour_process' => 120],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ALEPTM', 'name' => 'LEPTOSPIRA ANTICUERPOS IgM', 'name_report' => null, 'hour_process' => 120],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ANTSLA', 'name' => 'ANTÍGENO SOLUBLE EN HÍGADO (SLA) ANTICUERPOS', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Semen'], 'code' => 'AESPER', 'name' => 'ANTICUERPOS ANTI-ESPERMATOZOIDES', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'HLAB27', 'name' => 'HLA B*27 (ANTÍGENO LEUCOCITARIO HUMANO SUBTIPO 27) (PCR)', 'name_report' => null, 'hour_process' => 168],
                ['samples' => ['Suero (Rojo)'], 'code' => 'AINSUL', 'name' => 'AC. ANTI INSULINA', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ACENTR', 'name' => 'ANTI - CENTROMERO B', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ANEUTR', 'name' => 'AC. NEUTROFILOS ANCAS (ANCAS C, ANCAS P, ANCAS ATIPICO)', 'name_report' => 'ANCAS', 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ASMA', 'name' => 'ANTI MUSCULO LISO', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ICA', 'name' => 'ANTI ISLOTE PANCREATICO (ANTI ICA)', 'name_report' => null, 'hour_process' => 72],
                ['samples' => ['Suero (Rojo)'], 'code' => 'AMBG', 'name' => 'ANTICUEPOS ANTI MEMBRANA BASAL GLOMERULAR', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'FOSLIA', 'name' => 'ANTIFOSFOLIPIDOS IgA', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ALFA2', 'name' => 'ALFA 2 MICROGLOBULINA', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'B2GP1G', 'name' => 'ANTI-BETA 2 GLICOPROTEINA I IgG', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'B2GP1S', 'name' => 'ANTI-BETA 2 GLICOPROTEINA I SCREENING (IgG, IgM, IgA)', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ANGLIS', 'name' => 'ANTI GLIADINA SCRENING (IgG+IgA)', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'AFINT', 'name' => 'ANTI FACTOR INTRINSICO IgG', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'TRANSM', 'name' => 'TRANSGLUTAMINASA TISULAR IgM', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'GASTRO', 'name' => 'GASTRO WESTERN BLOT', 'name_report' => null, 'hour_process' => 72],
                ['samples' => ['Suero (Rojo)'], 'code' => 'AOVARG', 'name' => 'ANTICUERPOS IgG ANTI OVARIO EN SUERO', 'name_report' => null, 'hour_process' => 120],
                ['samples' => ['Suero (Rojo)'], 'code' => 'LEPTIN', 'name' => 'LEPTINA', 'name_report' => null, 'hour_process' => 240],
                ['samples' => ['Suero (Rojo)'], 'code' => 'CARDIS', 'name' => 'CARDIOLIPINAS (SCREENING IgG+IgA+IgM)', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'PMIOSI', 'name' => 'PANEL MIOSITIS', 'name_report' => null, 'hour_process' => 72],
                ['samples' => ['Suero (Rojo)'], 'code' => 'BETA2', 'name' => 'BETA 2 MICROGLOBULINA (SUERO)', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'CA724', 'name' => 'MARCADOR TUMORAL CA 72-4', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'CYFRA2', 'name' => 'CYFRA 21-1 (CARCINOMA ESCAMOSO-PULMÓN)', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'NSE', 'name' => 'NEUROENOLASA', 'name_report' => null, 'hour_process' => 360],
                ['samples' => ['Suero (Rojo)'], 'code' => 'MIOGLO', 'name' => 'MIOGLOBINA', 'name_report' => null, 'hour_process' => 4],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'BNP', 'name' => 'NtproBNP (PEPTIDO NATRIURETICO CARDIACA)', 'name_report' => null, 'hour_process' => 3],
                ['samples' => ['Hisopado Nasofaringeo'], 'code' => 'PANELI', 'name' => 'PANEL DE ALERGENOS INHALATORIOS', 'name_report' => null, 'hour_process' => 96],
                ['samples' => ['Suero (Rojo)'], 'code' => 'PNELIA', 'name' => 'PANEL DE ALERGENOS INHALATORIOS + ALIMENTARIOS', 'name_report' => null, 'hour_process' => 72],
                ['samples' => ['Suero (Rojo)'], 'code' => 'PNELA', 'name' => 'PANEL DE ALERGENOS ALIMENTARIOS', 'name_report' => null, 'hour_process' => 96],
                ['samples' => ['Suero (Rojo)'], 'code' => 'PANELP', 'name' => 'PANEL DE 20 ALERGENOS PEDIATRICO', 'name_report' => null, 'hour_process' => 96],
                ['samples' => ['Secreción Nasal'], 'code' => 'EOSINO', 'name' => 'EOSINOFILOS EN MOCO NASAL', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'MHTFR', 'name' => 'ANALISIS DE LA MUTACIÓN C677T EN EL GEN MTHFR', 'name_report' => null, 'hour_process' => 120],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'BCR/AB', 'name' => 'TRANSLOCACION  BCR/ABL CUALITATIVA (P190 P210)', 'name_report' => null, 'hour_process' => 120],
                ['samples' => ['Gotas de sangre en papel FTA'], 'code' => 'PATERN', 'name' => 'PRUEBA DE PATERNIDAD (2 INDIVIDUOS)', 'name_report' => null, 'hour_process' => 240],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'BCRCLT', 'name' => 'TRANSLOCACION BCR/ABL (P210) CUANTITATIVA', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Cepillado Cervico-vaginal'], 'code' => 'CHLADE', 'name' => 'CLAMYDIA TRACHOMATIS DNA DETECTOR', 'name_report' => null, 'hour_process' => 96],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'PMLRAR', 'name' => 'PML RARa T(15 17) (RT PCR)', 'name_report' => null, 'hour_process' => 120],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'JAK2', 'name' => 'ESTUDIO MOLECULAR DEL GEN JAK2 (JANUS KINASE) MUTACION V617F', 'name_report' => null, 'hour_process' => 120],
                ['samples' => ['Esputo'], 'code' => 'MYCOTB', 'name' => 'DETECCIÓN DE MYCOBACTERIUM TUBERCULOSIS', 'name_report' => null, 'hour_process' => 96],
                ['samples' => ['Hisopado Nasofaringeo'], 'code' => 'INFH1N', 'name' => 'INFLUENZA H1N1/A/B DNA DETECTOR', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'FIBROT', 'name' => 'FIBROTEST', 'name_report' => null, 'hour_process' => 96],
                ['samples' => ['Suero (Rojo)'], 'code' => 'FIBROM', 'name' => 'FIBROMAX', 'name_report' => null, 'hour_process' => 96],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'P13Q22', 'name' => 'INVERSION 16 (p13;q22)', 'name_report' => null, 'hour_process' => 120],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'PARVOV', 'name' => 'PARVOVIRUS B19 DNA DETECTOR', 'name_report' => null, 'hour_process' => 96],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'FIBQUP', 'name' => 'FIBROSIS QUISTICA PANEL 10 MUTACIONES', 'name_report' => null, 'hour_process' => 360],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'FIBQUS', 'name' => 'FIBROSIS QUISTICA SECUENCIACION 27 EXONES DEL GEN CFTR', 'name_report' => null, 'hour_process' => 720],
                ['samples' => ['Sangre Total Heparinizada (Verde)'], 'code' => 'FRACRO', 'name' => 'ESTUDIO DE FRAGILIDAD CROMOSOMICA', 'name_report' => null, 'hour_process' => 720],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'EA2-PB', 'name' => 'TRANSLOCACION E2A-PBX1 (t1;19)', 'name_report' => null, 'hour_process' => 120],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'MLLAF4', 'name' => 'TRANSLOCACION MLL-AF4 (t1;19)', 'name_report' => null, 'hour_process' => 120],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'TELAML', 'name' => 'TRANSLOCACION (12;21) TEL-AML1', 'name_report' => null, 'hour_process' => 120],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'AML1ET', 'name' => 'TRANSLOCACION (AML1 ETO)', 'name_report' => null, 'hour_process' => 120],
                ['samples' => ['Plasma con EDTA'], 'code' => 'BKCARV', 'name' => 'BK POLIOMAVIRUS EN PLASMA DNA CARGA VIRAL', 'name_report' => null, 'hour_process' => 96],
                ['samples' => ['Liquido Cefalorraquideo', 'Esputo', 'Suero (Rojo)', 'Plasma (Verde)'], 'code' => 'CMVCAR', 'name' => 'CARGA VIRAL DE CITOMEGALOVIRUS', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'EPSTEI', 'name' => 'EPSTEIN BARR DNA CARGA VIRAL', 'name_report' => null, 'hour_process' => 96],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'PAI-1', 'name' => 'DETECCIÓN DEL POLIMORFISMO 4G/5G EN EL GEN PAI-1', 'name_report' => null, 'hour_process' => 120],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'CHIRNA', 'name' => 'CHIKUNGUNYA RNA', 'name_report' => null, 'hour_process' => 96],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'EPST', 'name' => 'EPSTEIN BARR VIRUS RT-PCR', 'name_report' => null, 'hour_process' => 96],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'ZIKARN', 'name' => 'ZIKA RNA', 'name_report' => null, 'hour_process' => 96],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'CADSAN', 'name' => 'CADMIO EN SANGRE', 'name_report' => null, 'hour_process' => 96],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'VARETI', 'name' => 'VITAMINA A (RETINOL)', 'name_report' => null, 'hour_process' => 96],
                ['samples' => ['Orina'], 'code' => 'ALUMOR', 'name' => 'ALUMINIO EN ORINA PARCIAL', 'name_report' => null, 'hour_process' => 120],
                ['samples' => ['Orina'], 'code' => 'ALUMO-24', 'name' => 'ALUMINIO EN ORINA DE 24 HORAS', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ALUMSU', 'name' => 'ALUMINIO EN SUERO O PLASMA', 'name_report' => null, 'hour_process' => 96],
                ['samples' => ['Orina'], 'code' => 'COBROP', 'name' => 'COBRE EN ORINA PARCIAL', 'name_report' => null, 'hour_process' => 120],
                ['samples' => ['Orina'], 'code' => 'COBRO-24', 'name' => 'COBRE EN ORINA DE 24 HORAS', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Orina'], 'code' => 'A5HIDR', 'name' => 'ACIDO 5 HIDROXIINDOACETICO', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Orina'], 'code' => 'AMUCON', 'name' => 'ACIDO tt MUCONICO', 'name_report' => null, 'hour_process' => 240],
                ['samples' => ['Orina'], 'code' => 'AMETIL', 'name' => 'ACIDO METIL HIPURICO', 'name_report' => null, 'hour_process' => 240],
                ['samples' => ['Orina'], 'code' => 'AHIPUR', 'name' => 'ACIDO HIPURICO (METABOLITO DE TOLUENO) EN ORINA', 'name_report' => null, 'hour_process' => 240],
                ['samples' => ['Orina'], 'code' => 'CBTX-O', 'name' => 'PERFIL BTX EN ORINA (EXPOSICION A BENCENO, TOLUENO, XILENO)', 'name_report' => null, 'hour_process' => 240],
                ['samples' => ['Orina'], 'code' => 'AMANDE', 'name' => 'ACIDO MANDELICO + FENILGLIOXILICO (MTB DE ESTIRENO Y ETILBE)', 'name_report' => null, 'hour_process' => 480],
                ['samples' => ['Orina'], 'code' => 'AMAND', 'name' => 'ACIDO MANDELICO', 'name_report' => null, 'hour_process' => 480],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ZINC', 'name' => 'ZINC', 'name_report' => null, 'hour_process' => 240],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'PLOMOS', 'name' => 'PLOMO EN SANGRE', 'name_report' => null, 'hour_process' => 144],
                ['samples' => ['Orina'], 'code' => 'PLOMOO', 'name' => 'PLOMO EN ORINA', 'name_report' => null, 'hour_process' => 120],
                ['samples' => ['Orina'], 'code' => 'CADM-O', 'name' => 'CADMIO EN ORINA', 'name_report' => null, 'hour_process' => 169],
                ['samples' => ['Orina'], 'code' => 'FENO-O', 'name' => 'FENOLES EN ORINA', 'name_report' => null, 'hour_process' => 240],
                ['samples' => ['Suero (Rojo)'], 'code' => 'IL6', 'name' => 'INTERLEUKINA (IL-6)', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'FACNEC', 'name' => 'FACTOR DE NECROSIS TUMORAL', 'name_report' => null, 'hour_process' => 720],
                ['samples' => ['Gotas de sangre en papel FTA'], 'code' => 'TAMNEO', 'name' => 'TAMIZAJE METABÓLICO NEONATAL', 'name_report' => null, 'hour_process' => 120],
                ['samples' => ['Biopsia'], 'code' => 'BIOPB', 'name' => 'BIOPSIAS DE BAJA COMPLEJIDAD', 'name_report' => null, 'hour_process' => 120],
                ['samples' => ['Biopsia'], 'code' => 'BIOPM', 'name' => 'BIOPSIAS DE MEDIANA COMPLEJIDAD', 'name_report' => null, 'hour_process' => 120],
                ['samples' => ['Biopsia'], 'code' => 'BIOPA', 'name' => 'BIOPSIAS DE ALTA COMPLEJIDAD', 'name_report' => null, 'hour_process' => 120],
                ['samples' => ['Coloracion Papanicolaou'], 'code' => 'PAPTES', 'name' => 'PAPANICOLAOU (TEST-CITOLOGIA CERVICOVAGINAL CONVENCIONAL)', 'name_report' => null, 'hour_process' => 72],
                ['samples' => ['Muestra oncologica'], 'code' => 'ONCOLO', 'name' => 'MUESTRAS ONCOLOGICAS', 'name_report' => null, 'hour_process' => 72],
                ['samples' => ['Orina'], 'code' => 'EMB-O', 'name' => 'HCG BETA CUALITATIVO (TEST DE EMBARAZO EN ORINA)', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'GAD', 'name' => 'ACIDO GLUTAMICO DECARBOXILASA (GAD65) ANTICUERPOS', 'name_report' => null, 'hour_process' => 240],
                ['samples' => ['Orina'], 'code' => 'BETA2O', 'name' => 'BETA 2 MICROGLOBULINA (ORINA)', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ALD', 'name' => 'ALDOSA', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Plasma con EDTA'], 'code' => 'BUTIRI', 'name' => 'BUTIRIL COLINESTERASA', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'GLUC6P', 'name' => 'GLUCOSA 6 PHD (FOSFATO DESHIDROGENASA)', 'name_report' => null, 'hour_process' => 72],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ELECPS', 'name' => 'ELECTROFORESIS DE PROTEÍNAS EN SANGRE', 'name_report' => null, 'hour_process' => 240],
                ['samples' => ['Orina'], 'code' => 'YODO-O', 'name' => 'YODUROS EN ORINA', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'HAPTO', 'name' => 'HAPTOGLOBINA', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'SCRENE', 'name' => 'SCRENING METABOLICO NEONATAL', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'HOMO', 'name' => 'HOMOCISTEINA', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'SIRO', 'name' => 'SIROLIMUS (INDICAR HORA DE TOMA E INGESTA DE MEDICAMENTO)', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Orina'], 'code' => 'BENZO', 'name' => 'BENZODIACEPINAS', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'CARBAM', 'name' => 'CARBAMAZEPINA', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'CICLO', 'name' => 'CICLOSPORINA (INDICAR HORA DE MUESTRA Y DOSIS)', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Plasma con EDTA'], 'code' => 'DIGOX', 'name' => 'DIGOXINA', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'FENIT', 'name' => 'FENITOINA (DIFENIHHIDANTOÍNA-EPAMÍN)', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'FENOB', 'name' => 'FENOBARBITAL', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'TEOF', 'name' => 'TEOFILINA', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Orina'], 'code' => 'BARB', 'name' => 'BARBITURICOS', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Orina'], 'code' => 'METAN', 'name' => 'METANFETAMINAS', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Orina'], 'code' => 'NICOO', 'name' => 'NICOTINA EN ORINA', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Orina'], 'code' => 'MORF', 'name' => 'MORFINA', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'VANCO', 'name' => 'VANCOMICINA', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'CRIOA', 'name' => 'CRIOAGLUTININAS', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Orina'], 'code' => 'CORTIO', 'name' => 'CORTISOL EN ORINA PARCIAL', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Orina'], 'code' => 'CORT-24', 'name' => 'CORTISOL EN ORINA DE 24 HORAS', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'IGFBP3', 'name' => 'IGF BP3', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'DOBLET', 'name' => 'DOBLE TEST', 'name_report' => null, 'hour_process' => 120],
                ['samples' => ['Suero (Rojo)'], 'code' => 'TSCRE', 'name' => 'TRIPLE SCREENING CALCULO', 'name_report' => null, 'hour_process' => 120],
                ['samples' => ['Suero 30MIN (Rojo)', 'Suero 3H (Rojo)', 'Suero 2H (Rojo)', 'Suero (Rojo)'], 'code' => 'CINSUL', 'name' => 'CURVA DE INSULINA 3 HORAS', 'name_report' => null, 'hour_process' => 3],
                ['samples' => ['Suero 2H (Rojo)', 'Suero 30MIN (Rojo)', 'Suero (Rojo)'], 'code' => 'CINS2', 'name' => 'CURVA DE INSULINA 2 HORAS', 'name_report' => null, 'hour_process' => 2],
                ['samples' => ['Suero (Rojo)'], 'code' => 'INSUP', 'name' => 'INSULINA POSTPRANDIAL', 'name_report' => null, 'hour_process' => 4],
                ['samples' => ['Suero (Rojo)'], 'code' => 'GLBHOR', 'name' => 'GLOBULINA TRANSPORTADORA DE HORMONAS SEXUALES', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ABORRG', 'name' => 'BORRELIA GURGDOFERI ANTICUERPOS IgG', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'SERAME', 'name' => 'AMEBA HISTOLYTICA (ANTICUERPOS SERICOS) SERAMOEBA', 'name_report' => null, 'hour_process' => 72],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ABORRM', 'name' => 'BORRELIA GURGDOFERI ANTICUERPOS IgM', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'CISTG', 'name' => 'CISTICERCO ANTICUERPOS IgG', 'name_report' => null, 'hour_process' => 72],
                ['samples' => ['Suero (Rojo)'], 'code' => 'EBVCAG', 'name' => 'EPSTEIN BARR ANTÍGENO DE CÁPSIDE IGG (VCA IGG)', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'EBVCAM', 'name' => 'EPSTEIN BARR  ANTÍGENO DE CÁPSIDE IGM (VCA IGM)', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Esputo'], 'code' => 'MYCORI', 'name' => 'MYCOBACTERIUM T + RESISTENCIA A LA RIFANPICINA', 'name_report' => null, 'hour_process' => 96],
                ['samples' => ['Sangre Citrato (Celeste)'], 'code' => 'PDF', 'name' => 'PRODUCTO DE DEGRADACIÓN DE FIBRINÓGENO', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Muestras Varias'], 'code' => 'BIPGRA', 'name' => 'BIOPSIA DE GRAN COMPLEJIDAD', 'name_report' => null, 'hour_process' => 192],
                ['samples' => ['Orina'], 'code' => 'PANELD', 'name' => 'PANEL DROGAS EN ORINA', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'CROMOA', 'name' => 'CROMOGRANINA A', 'name_report' => null, 'hour_process' => 120],
                ['samples' => ['Suero (Rojo)'], 'code' => 'PANELN', 'name' => 'PANEL DE NEUMONIA ATIPICA', 'name_report' => null, 'hour_process' => 92],
                ['samples' => ['Suero (Rojo)'], 'code' => 'TRANSC', 'name' => 'TRANSGLUTAMINASA Ttg (IgG+IgA) SCREENING', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'LIWEST', 'name' => 'LIVER WESTERN BLOT', 'name_report' => null, 'hour_process' => 92],
                ['samples' => ['Muestras Varias'], 'code' => 'CITOPU', 'name' => 'PUNCIONES O CITOLOGIA ESPECIAL (6 PLACAS)', 'name_report' => null, 'hour_process' => 96],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'FLD', 'name' => 'FORMULA LEUCOCITARIA DIFERENCIAL', 'name_report' => null, 'hour_process' => 1],
                ['samples' => ['Suero (Rojo)'], 'code' => 'FRCUA', 'name' => 'FACTOR REUMATOIDE CUANTITATIVO IGM', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Muestras Varias'], 'code' => 'CITO', 'name' => 'CITOBACTERIOLOGICO DE SECRECION VAGINAL', 'name_report' => null, 'hour_process' => 72],
                ['samples' => ['Orina'], 'code' => 'PROTOP', 'name' => 'PROTEINURIA EN ORINA PARCIAL', 'name_report' => null, 'hour_process' => 1],
                ['samples' => ['Suero (Rojo)'], 'code' => 'TROPI', 'name' => 'TROPONINA I', 'name_report' => null, 'hour_process' => 1],
                ['samples' => ['Liquidos Varios'], 'code' => 'CITOQ', 'name' => 'CITOQUIMICO Y BACTERIOLOGICO DE LIQUIDOS', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Sangre Arterial'], 'code' => 'GASOAR', 'name' => 'GASOMETRIA ARTERIAL', 'name_report' => null, 'hour_process' => 1],
                ['samples' => ['Suero (Rojo)'], 'code' => 'GASOVE', 'name' => 'GASOMETRIA VENOSA', 'name_report' => null, 'hour_process' => 1],
                ['samples' => ['Suero (Rojo)'], 'code' => 'FESTRA', 'name' => 'ESTRADIOL LIBRE', 'name_report' => null, 'hour_process' => 1],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ESTRON', 'name' => 'ESTRONA', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Sangre Citrato (Celeste)'], 'code' => 'TC', 'name' => 'TIEMPO DE COAGULACIÓN', 'name_report' => null, 'hour_process' => 1],
                ['samples' => ['Sangre Citrato (Celeste)'], 'code' => 'TS', 'name' => 'TIEMPO DE SANGRIA', 'name_report' => null, 'hour_process' => 1],
                ['samples' => ['Liquidos Varios'], 'code' => 'CITOLI', 'name' => 'CITOLOGÍA DE LÍQUIDOS', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Muestras Varias'], 'code' => 'ESTEA', 'name' => 'ESTEARASA', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Secreción Nasal'], 'code' => 'EOSIN2', 'name' => 'EOSINÓFILOS EN MOCO NASAL DIA 2', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Secreción Nasal'], 'code' => 'EOSIN3', 'name' => 'EOSINÓFILOS EN MOCO NASAL DIA 3', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'HPVSER', 'name' => 'HPV SERICO IgM', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'IGEPEN', 'name' => 'IGE ESPECÍFICA PENICILINA', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'IGEAMO', 'name' => 'IGE ESPECÍFICA AMOXACILINA', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'CISTA', 'name' => 'CISTATINA C', 'name_report' => null, 'hour_process' => 2],
                ['samples' => ['Materia Fecal'], 'code' => 'CALPRO', 'name' => 'CALPROTECTINA', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Secreción Nasal'], 'code' => 'STREPB', 'name' => 'ANTÍGENO DE ESTREPTOCOCO GRUPO B (STREP B TEST)', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ESCOPO', 'name' => 'ESCOPOLAMINA', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'LIPID', 'name' => 'LIPIDOS TOTALES', 'name_report' => null, 'hour_process' => 3],
                ['samples' => ['Muestras Varias'], 'code' => 'ZIEHL2', 'name' => 'ZIEHL- BAAR DIA 2', 'name_report' => null, 'hour_process' => 4],
                ['samples' => ['Muestras Varias'], 'code' => 'ZIEHL3', 'name' => 'ZIEHL- BAAR DIA 3', 'name_report' => null, 'hour_process' => 4],
                ['samples' => ['Suero (Rojo)'], 'code' => 'HIVWES', 'name' => 'HIV WESTERN BLOT', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'PLASFA', 'name' => 'PLASMODIUM FALCIPARUM', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'PLASVI', 'name' => 'PLASMODIUM VIVAX', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'CELULE', 'name' => 'CELULAS LE', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'INMUNO', 'name' => 'INMUNOCOMPLEJO CIRCULANTE', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'PAROTI', 'name' => 'PAROTIDITIS IGM', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'AMON', 'name' => 'AMONIO', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Materia Fecal'], 'code' => 'NOROVI', 'name' => 'NOROVIRUS', 'name_report' => null, 'hour_process' => 4],
                ['samples' => ['Suero (Rojo)'], 'code' => 'PREALB', 'name' => 'PREALBUMINA', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Orina Cultivo'], 'code' => 'UROC', 'name' => 'UROCULTIVO', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ISAT', 'name' => 'INDICE DE SATURACIÓN DE TRANSFERRINA', 'name_report' => null, 'hour_process' => 4],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'RETRAC', 'name' => 'RETRACCIÓN DE COÁGULO', 'name_report' => null, 'hour_process' => 4],
                ['samples' => ['Sangre Citrato (Celeste)'], 'code' => 'FVONV', 'name' => 'FACTOR VON WILLEBRANT', 'name_report' => null, 'hour_process' => 4],
                ['samples' => ['Suero (Rojo)'], 'code' => 'COVPR', 'name' => 'SARS-CoV-2 IgG / IgM Antibody', 'name_report' => null, 'hour_process' => 2],
                ['samples' => ['Suero (Rojo)'], 'code' => 'COVCNT', 'name' => 'CUANTITATIVA SARS COV 2 COVID-19 ANTICUERPOS', 'name_report' => null, 'hour_process' => 2],
                ['samples' => ['Hisopado Nasofaringeo'], 'code' => 'COVPCR', 'name' => 'CORONAVIRUS SARS-CoV-2 RT-PCR', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Secreción Faríngea'], 'code' => 'CUNAFA', 'name' => 'CULTIVO DE SECRECIÓN FARÍNGEA', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Muestras Varias'], 'code' => 'HEMOC2', 'name' => 'HEMOCULTIVO MUESTRA 2', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Muestras Varias'], 'code' => 'HEMOC3', 'name' => 'HEMOCULTIVO MUESTRA 3', 'name_report' => null, 'hour_process' => 72],
                ['samples' => ['Esputo'], 'code' => 'CULESP', 'name' => 'CULTIVO DE ESPUTO', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Secreción Traqueal'], 'code' => 'CULTRA', 'name' => 'CULTIVO DE SECRECIÓN TRAQUEAL', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Líquido Pleural'], 'code' => 'CUPLEU', 'name' => 'CULTIVO DE LÍQUIDO PLEURAL', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Muestras Varias'], 'code' => 'CUANAE', 'name' => 'CULTIVO DE ANAEROBIOS', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Muestras Varias'], 'code' => 'CULBA1', 'name' => 'CULTIVO DE BAAR 1 MUESTRA', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Muestras Varias'], 'code' => 'CULBA2', 'name' => 'CULTIVO DE BAAR 2 MUESTRA', 'name_report' => null, 'hour_process' => 72],
                ['samples' => ['Muestras Varias'], 'code' => 'CULBA3', 'name' => 'CULTIVO DE BAAR 3 MUESTRA', 'name_report' => null, 'hour_process' => 72],
                ['samples' => ['Suero (Rojo)'], 'code' => 'HGH60M', 'name' => 'HORMONA DE CRECIMIENTO HGH 60 MIN', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'HGH90M', 'name' => 'HORMONA DE CRECIMIENTO HGH 90 MIN', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'HTLV', 'name' => 'HTLV - I / II', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'VITD', 'name' => 'VITAMINA D', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'COBRES', 'name' => 'COBRE EN SUERO', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'LAMO', 'name' => 'LAMOTRIGINA (LAMIGTAL)', 'name_report' => null, 'hour_process' => 72],
                ['samples' => ['Suero (Rojo)'], 'code' => 'CATECO', 'name' => 'CATECOLAMINAS EN ORINA DE 24 HORAS', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'AMULLE', 'name' => 'HORMONA ANTI-MÜLLERIANA', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'VITB1', 'name' => 'VITAMINA B1', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'PAPPA', 'name' => 'PROTEÍNA A. ASOCIADA AL EMBARAZO (PAPP A)', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'HCGL', 'name' => 'HCG FREE', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Semen'], 'code' => 'BRUC', 'name' => 'BRUCELLA ABORTUS, ANTICUERPOS IGG + IGM', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'TORCH', 'name' => 'TORCH PRUEBA RÁPIDA', 'name_report' => null, 'hour_process' => 1],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ALFA1', 'name' => 'ALFA 1 ANTITRIPSINA', 'name_report' => null, 'hour_process' => 72],
                ['samples' => ['Suero (Rojo)'], 'code' => 'CERULO', 'name' => 'CERULOPLASMINA', 'name_report' => null, 'hour_process' => 72],
                ['samples' => ['Muestras Varias'], 'code' => 'CUVAR2', 'name' => 'CULTIVO Y ANTIBIOGRAMA MUESTRAS VARIAS 2', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'HELIPR', 'name' => 'HELICOBACTER PYLORI PRUEBA RÁPIDA', 'name_report' => null, 'hour_process' => 2],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ESTRI', 'name' => 'ESTRIOL', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Saliva'], 'code' => 'CORSAL', 'name' => 'CORTISOL EN SALIVA', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'BRUCEL', 'name' => 'INVESTIGACIÓN DE BRUCELOSIS', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Sangre Total EDTA (Lila)'], 'code' => 'FROTIS', 'name' => 'FROTIS DE SANGRE PERIFERICA', 'name_report' => null, 'hour_process' => 2],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ROMA', 'name' => 'INDICE ROMA, RELACION HE4-CA125', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Hisopado Nasofaringeo'], 'code' => 'COVAG', 'name' => 'ANTIGENOS SARS-CoV-2 Ag', 'name_report' => null, 'hour_process' => 4],
                ['samples' => ['Suero (Rojo)'], 'code' => 'PAPPA1', 'name' => 'ÍNDICE DE RIESGO PRENATAL PRIMER TRIMESTRE', 'name_report' => null, 'hour_process' => 72],
                ['samples' => ['Suero (Rojo)'], 'code' => 'PAPPA2', 'name' => 'ÍNDICE DE RIESGO PRENATAL SEGUNDO TRIMESTRE', 'name_report' => null, 'hour_process' => 72],
                ['samples' => ['Suero (Rojo)'], 'code' => 'RASTCH', 'name' => 'RAST DE CLARA DE HUEVO', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'RASTYH', 'name' => 'RAST DE YEMA DE HUEVO', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'RASTCE', 'name' => 'RAST DE CERDO', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'LEVETI', 'name' => 'NIVELES SÉRICOS DE LEVIRACETAN', 'name_report' => null, 'hour_process' => 72],
                ['samples' => ['Suero (Rojo)'], 'code' => 'WFELIX', 'name' => 'AGLUTINACIONES FEBRILES (TEST DE WEIL-FELIX)', 'name_report' => null, 'hour_process' => 2],
                ['samples' => ['Suero (Rojo)'], 'code' => 'HUDDLE', 'name' => 'AGLUTINACIONES FEBRILES (TEST DE HUDDLE)', 'name_report' => null, 'hour_process' => 2],
                ['samples' => ['Suero (Rojo)'], 'code' => 'DENIM', 'name' => 'ANTI DENGUE IGM', 'name_report' => null, 'hour_process' => 4],
                ['samples' => ['Suero (Rojo)'], 'code' => 'NS1', 'name' => 'DENGUE NS1', 'name_report' => null, 'hour_process' => 4],
                ['samples' => ['Orina'], 'code' => 'COTI', 'name' => 'COTININA EN ORINA', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Suero (Rojo)'], 'code' => 'HOMAIR', 'name' => 'ÍNDICE HOMA', 'name_report' => null, 'hour_process' => 2],
                ['samples' => ['Orina'], 'code' => 'PYRILIN', 'name' => 'PYRILINKS-D', 'name_report' => null, 'hour_process' => 4],
                ['samples' => ['Suero (Rojo)'], 'code' => 'B2GP1A', 'name' => 'ANTI-BETA 2 GLICOPROTEINA I IgA', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'RASTPER', 'name' => 'RAST DE CASPA DE PERRO', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'RASTAC', 'name' => 'RAST DE ÁCARO COMÚN (SIRO)', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'RASTGAT', 'name' => 'RAST DE CASPA DE GATO', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Suero (Rojo)'], 'code' => 'COVRBD', 'name' => 'SARS-CoV-2 S-RBD IgG', 'name_report' => null, 'hour_process' => 4],
                ['samples' => ['Suero (Rojo)'], 'code' => 'AGLU', 'name' => 'AGLUTINACIONES FEBRILES COMPLETAS', 'name_report' => null, 'hour_process' => 3],
                ['samples' => ['Suero (Rojo)'], 'code' => 'PCRCNT', 'name' => 'PCR PROTEINA C REACTIVA CUANTITATIVA', 'name_report' => null, 'hour_process' => 4],
                ['samples' => ['Suero (Rojo)'], 'code' => 'PCRSCNT', 'name' => 'PCR PROTEINA C REACTIVA SEMICUANTITATIVA', 'name_report' => null, 'hour_process' => 4],
                ['samples' => ['Suero (Rojo)'], 'code' => 'ELECTRO', 'name' => 'ELECTROLITOS SODIO POTASIO CLORO', 'name_report' => null, 'hour_process' => 2],
                ['samples' => ['Sangre Total EDTA2 (Lila)'], 'code' => 'BHVSG', 'name' => 'BIOMETRIA HEMATICA+VSG', 'name_report' => null, 'hour_process' => 2],
                ['samples' => ['Suero (Rojo)'], 'code' => 'BHDON', 'name' => 'BIOMETRIA HEMATICA DONANTE', 'name_report' => null, 'hour_process' => 2],
                ['samples' => ['Muestras Varias'], 'code' => 'CULAB', 'name' => 'CULTIVO ABDOMINAL', 'name_report' => null, 'hour_process' => 72],
                ['samples' => ['Muestras Varias'], 'code' => 'CULAMB', 'name' => 'CULTIVO DE AMBIENTE', 'name_report' => null, 'hour_process' => 72],
                ['samples' => ['Suero 3H (Rojo)', 'Suero 3H (Rojo)', 'Suero 2H (Rojo)', 'Suero 1H (Rojo)', 'Suero (Rojo)'], 'code' => 'CURV4H', 'name' => 'CURVA DE GLUCOSA 4 HORAS', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Plasma (Verde)', 'Liquido Cefalorraquideo'], 'code' => 'HERPA', 'name' => 'PANEL DE HERPES', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Plasma con EDTA'], 'code' => 'ENTEROV', 'name' => 'Enterovirus por ADN/PCR', 'name_report' => null, 'hour_process' => 72],
                ['samples' => ['Plasma (Verde)', 'Liquido Cefalorraquideo'], 'code' => 'PME', 'name' => 'PANEL DE MENINGITIS/ENCEFALITIS', 'name_report' => null, 'hour_process' => 72],
                ['samples' => ['Plasma con EDTA'], 'code' => 'PNV', 'name' => 'PANEL NEUROLÓGICO VIRAL', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Plasma (Verde)', 'Liquido Cefalorraquideo'], 'code' => 'PHV', 'name' => 'PANEL HERPES VIRUS', 'name_report' => null, 'hour_process' => 48],
                ['samples' => ['Cepillado Cervico-vaginal', 'Secreción Vaginal'], 'code' => 'PETS', 'name' => 'PANEL DE ENFERMEDADES DE TRANSMISIÓN SEXUAL', 'name_report' => null, 'hour_process' => 120],
                ['samples' => ['Materia Fecal'], 'code' => 'PGI', 'name' => 'PANEL GASTROINTESTINAL', 'name_report' => null, 'hour_process' => 96],
                ['samples' => ['Sangre Total EDTA2 (Lila)'], 'code' => 'PLA7M', 'name' => 'PANEL DE LEUCEMIA AGUDA 7 MARCADORES', 'name_report' => null, 'hour_process' => 168],
                ['samples' => ['Liquido Cefalorraquideo'], 'code' => 'SBT', 'name' => 'SEPTITEST BACTERIAS TIPICAS', 'name_report' => null, 'hour_process' => 24],
                ['samples' => ['Tubo EDTA 4ml'], 'code' => 'MOL0001', 'name' => 'Carga Viral de Citomegalovirus (CMV) por PCR en tiempo real', 'name_report' => null, 'hour_process' => 120],
                ['samples' => ['Hisopado Nasofaringeo'], 'code' => 'COVXP', 'name' => 'SARS-CoV-2 PCR/Xpress', 'name_report' => null, 'hour_process' => 2],
                ['samples' => ['Hisopado Nasofaringeo'], 'code' => 'COVXPRE', 'name' => 'Influenza A-B, RSV y SARS-CoV-2 por PCR/Xpress', 'name_report' => null, 'hour_process' => 3],
            ];
            foreach ($arr_distribution as $value) {
                $Exams = Exams::firstOrCreate([
                    'code' => $value['code'],
                    'name' => $value['name'],
                    'name_report' => $value['name_report'],
                    'hour_process' => $value['hour_process'],
                    'created_by_user' => $user->id,
                ]);

                //--- CREACION CABECERA DE LAS MUESTRAS
                $RelationSamplesHeader = RelationSamplesHeader::firstOrCreate([
                    'tbl_exams' => $Exams->id,
                    'created_by_user' => $user->id,
                ]);

                //-- ACTUALIZAR CAMPO 'tbl_exams_samples_main' DE LA TABLA EXAMS
                Exams::where('id', $Exams->id)->update([
                    'tbl_exams_samples_main' => $RelationSamplesHeader->id,
                ]);

                $samples = $value['samples'];
                foreach ($samples as $sample) {
                    $info_sample = Samples::where('name', $sample)->first();
                    $RelationSamplesDetails = RelationSamplesDetails::firstOrCreate([
                        'tbl_exams_samples_main' => $RelationSamplesHeader->id,
                        'tbl_samples' => $info_sample->id,
                        'created_by_user' => $user->id,
                    ]);
                }
            }

            //--- CREACION DE TIPOS DE EXAMENES
            $arr_distribution = [
                ['code' => 'P', 'name' => 'Procesable'],
                ['code' => 'D', 'name' => 'Derivable'],
            ];
            foreach ($arr_distribution as $value) {
                $Type_exams = TypeExams::firstOrCreate([
                    'code' => $value['code'],
                    'name' => $value['name'],
                ]);
            }

            //--- CREACION DE CATEGORIAS/SECCIONES DE EXAMENES
            $arr_distribution = [
                ['order' => 1, 'name' => 'Hematología'],
                ['order' => 2, 'name' => 'Bioquímica'],
                ['order' => 3, 'name' => 'Química Clínica en Orina'],
                ['order' => 4, 'name' => 'Coproanálisis'],
                ['order' => 5, 'name' => 'Uroanálisis'],
                ['order' => 6, 'name' => 'Coagulación'],
                ['order' => 7, 'name' => 'Autoinmunes e Infecciosas'],
                ['order' => 8, 'name' => 'Estudios Hormonales'],
                ['order' => 9, 'name' => 'Serología'],
                ['order' => 10, 'name' => 'Electrolitos'],
                ['order' => 11, 'name' => 'Marcadores Tumorales'],
                ['order' => 12, 'name' => 'Marcadores Coronarios'],
                ['order' => 13, 'name' => 'Inmunoquímica Sanguínea'],
                ['order' => 14, 'name' => 'Drogas y Fármacos'],
                ['order' => 15, 'name' => 'Estudios de Alergias'],
                ['order' => 16, 'name' => 'Microbiología'],
                ['order' => 17, 'name' => 'Especiales'],
                ['order' => 18, 'name' => 'Citología'],
                ['order' => 19, 'name' => 'Líquidos Biológicos'],
                ['order' => 20, 'name' => 'Biología Molecular'],
                ['order' => 21, 'name' => 'Medicina Ocupacional'],

            ];
            foreach ($arr_distribution as $value) {
                $Type_exams = CategoryExams::firstOrCreate([
                    'order' => $value['order'],
                    'name' => $value['name'],
                    'created_by_user' => $user->id,
                ]);
            }

            // CREACION DE TIPOS DE PARAMETROS PARA LAS PLANTILLAS
            $arr_distribution = [
                ['code' => 'INPUT-TXT', 'name' => 'Input Texto'],
                ['code' => 'ADD-QR', 'name' => 'Agregar QR (Redireccionar archivo)'],
                ['code' => 'ADD-IMG', 'name' => 'Agregar imagen'],
                ['code' => 'ADD-SEP', 'name' => 'Separación (Salto linea)'],
                ['code' => 'INPUT-NUM', 'name' => 'Input Númerico'],
                ['code' => 'INPUT-OPT', 'name' => 'Lista Referencia'],
                ['code' => 'TIT', 'name' => 'Titulo'],
                // ['code'=> 'GLOS','name'=> 'Glosa'],
            ];
            foreach ($arr_distribution as $value) {
                $TypeParameterTemplate = TypeParameterTemplate::firstOrCreate([
                    'code' => $value['code'],
                    'name' => $value['name'],
                ]);
            }

            // CREACION DE CONFIGURACION DE INTERPRETACION DE PLANTILLAS
            $arr_distribution = [
                ['code' => 'DEFAULT', 'name' => 'Mostrar en la columna de referencia'],
                ['code' => 'C-EXM', 'name' => 'Mostrar en la columna de examen'],
                ['code' => 'N-LN', 'name' => 'Mostrar en una nueva linea'],
            ];
            foreach ($arr_distribution as $value) {
                $ConfigInterpretationParameter = ConfigInterpretationParameter::firstOrCreate([
                    'code' => $value['code'],
                    'name' => $value['name'],
                ]);
            }

            // CREACION DE CONFIGURACION DE ESCALA DE EDADES PARA PARAMETROS DE CONFIGURACION DE EXAMENES
            $arr_distribution = [
                ['code' => 'days', 'name' => 'Días'],
                ['code' => 'months', 'name' => 'Meses'],
                ['code' => 'years', 'name' => 'Años'],
            ];
            foreach ($arr_distribution as $value) {
                $ScaleParameterAge = ScaleParameterAge::firstOrCreate([
                    'code' => $value['code'],
                    'name' => $value['name'],
                ]);
            }

            // CREACION DE TIPOS DE AJUSTES DE PRECIOS
            $arr_distribution = [
                ['code' => 'F', 'name' => 'Valor fijo'],
                ['code' => 'P', 'name' => 'Porcentaje'],
            ];
            foreach ($arr_distribution as $value) {
                $TypeAdjustPrice = TypeAdjustPrice::firstOrCreate([
                    'code' => $value['code'],
                    'name' => $value['name'],
                ]);
            }

        }
    }
}
